### ISSUE TITLE
Zufällige Chest

### ISSUE THREAD

**Issue by charline98** [NullDev/Discord-RoleShop#4]
Eine zufällige Chest mit Points für den Rollenshop.
Es sollten mind. 4h zwischen den Drops sein, dann kann sie pro Nachricht mit einer Chance von 15% zufällig kommen. 
Es sollten zufällig so 10-80 Points enthalten sein. Der User, der als erstes klickt erhält die Chest. Die Chest sollte ablaufen können und sollte für maximal 2 min. verfügbar sein.

**Comment by NullDev** [comment]
Eingebaut: https://github.com/NullDev/Discord-RoleShop/commit/cb3c1aa4f43dc7ae0027625f353f9dfe41a55baf
